<%@ Page Title="" Language="C#" MasterPageFile="~/StudentMaster.master" AutoEventWireup="true" CodeFile="RegisteredCourse.aspx.cs" Inherits="_Default" %>
<%@ MasterType VirtualPath="~/StudentMaster.master" %>
<asp:Content ID="Content19" ContentPlaceHolderID="Heading1000" Runat="Server">
     <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Workshops
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="SDashboard.aspx">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-book"></i> Registration
                            </li>
                             <li class="active">
                                </i> Registered Workshops
                            </li>
                        </ol>
                    </div>
                </div>
</asp:Content>

<asp:Content ID="Content190" ContentPlaceHolderID="RegisteredCourse" Runat="Server">
     
                <asp:GridView runat="server" ID="gvCourse" OnRowDataBound="gvCourse_RowDataBound" CssClass="table table-bordered table-hover table-responsive" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateColumns="false">
                    <Columns>

                        <asp:BoundField ReadOnly="true" HeaderText="Course Id" DataField="Course Id" />
                      
                       
                        <asp:BoundField HeaderText="Course" DataField="Course" />
                        <asp:BoundField HeaderText="Instructor Name" DataField="Instructor Name" />
                        <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="lbDRegister" runat="server">De-register Course </asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>



       
   
       
</asp:Content>

