<%@ Page Title="" Language="C#" MasterPageFile="~/StudentMaster.master" AutoEventWireup="true" CodeFile="SDashboard.aspx.cs" Inherits="_Default" %>
<%@ MasterType VirtualPath="~/StudentMaster.master" %>

<asp:Content ID="Content163" ContentPlaceHolderID="DH" Runat="Server">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard
            </h1>

        </div>
    </div>
</asp:Content>
<asp:Content ID="Content171" ContentPlaceHolderID="DD" Runat="Server">
     <div class="row">
        <div class="col-lg-12">
             <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><i class="fa fa-book fa-fw"></i>Upcoming Workshops</h2>

                </div>
                <br />

             <center>     <asp:GridView ID="gvCourseRegistration" runat="server" CssClass="table  table-bordered table-responsive table-hover"   DataKeyNames="Course Id"
            AllowPaging="True" EnableViewState="False" Height="118px" Width="527px"  BorderStyle="Solid" BorderWidth="1" CellPadding="4" CellSpacing="2" ForeColor="Black"  >
              
                 <HeaderStyle BackColor="#151C47" ForeColor="White" />
           
            
          </asp:GridView> </center>


                <div class="panel-body">
                </div>
            </div>

                        <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><i class="fa fa-video-camera fa-fw"></i>Demo Lectures</h2>

                </div>
                <br />

 <center>  <asp:PlaceHolder ID="DBDataPlaceHolder" runat="server"></asp:PlaceHolder>  </center> 
        <div class="col-lg-12">
            <div class="center-block">
               
                <asp:GridView runat="server" DataKeyNames="Id" OnRowDataBound="grdStudents_RowDataBound"  ID="grdStudents" CssClass="table table-bordered table-hover table-responsive" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateColumns="false">
                    <Columns>

                        <asp:BoundField ReadOnly="true" HeaderText="Lecture No." DataField="Id"  />
                        
                        <asp:TemplateField HeaderText="Lecture Title">
                            <ItemTemplate>
                                <b>
                                    <asp:Label runat="server" Text='<%#Eval("LectureName") %>'></asp:Label></b>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField HeaderText="Lecture Description" DataField="LectureDescription" />
                         <asp:BoundField HeaderText="Lecturer" DataField="instructor_name" />
                        <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="Watch" runat="server" OnClick="Watch_Click">Watch Lecture</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        

                        
                    </Columns>
                </asp:GridView>
              
            </div>

        </div>


                <div class="panel-body">
                </div>
            </div>

          
        </div>
    </div>
</asp:Content>

