<%@ Page Title="" Language="C#" MasterPageFile="~/InstructorMaster.master" AutoEventWireup="true" CodeFile="UploadLectures.aspx.cs" Inherits="UploadLectures" %>
<%@ MasterType VirtualPath="~/InstructorMaster.master" %>
<asp:Content ID="Content5659" ContentPlaceHolderID="Heading386" Runat="Server">
     <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Courses
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i><a href="IDashboard.aspx"> Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-book"></i> Courses
                </li>
                <li class="active"></i> Upload Lectures
                </li>
            </ol>
        </div>
    </div>
</asp:Content>

<asp:Content ID="Content6" ContentPlaceHolderID="UploadLectures" Runat="Server">
    <center>  <asp:PlaceHolder ID="DBDataPlaceHolder" runat="server"></asp:PlaceHolder>  </center> 
        <div class="col-lg-12">
            <div class="center-block">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i>
                      Add New Lectures
									
                    </div>
                    <div class="panel-body">

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">
                                   Lecture Title
                                </label>

                                <input type="text" class="form-control" id="s_name" name="s_name" placeholder="Enter Name" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">
                                    Lecture Description
                                </label>

                                <input type="text" class="form-control" id="s_contact" name="s_contact" placeholder="Enter Number" />
                            </div>
                        </div>
                        <div class="col-md-6">
                           
                            <div class="form-group">
                                <label class="control-label">
                                    Upload Lecture
                                </label>

                                <asp:FileUpload runat="server" ID="s_file" />
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="col-sm-12">
                            <div class="pull-right">
                                <div class="form-group">
                                    <asp:Button runat="server" ID="AddStdnt" CssClass="btn btn-success" Text="Add Lecture" OnClick="AddStdnt_Click" />

                                </div>
                            </div>

                        </div>
                        <div class="clearfix"></div>
                    </div>

                </div>
                <asp:GridView runat="server" DataKeyNames="Id" OnRowDataBound="grdStudents_RowDataBound"  ID="grdStudents" CssClass="table table-bordered table-hover table-responsive" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateColumns="false">
                    <Columns>

                        <asp:BoundField ReadOnly="true" HeaderText="Student Id" DataField="Id"  />
                        
                        <asp:TemplateField HeaderText="Lecture Title">
                            <ItemTemplate>
                                <b>
                                    <asp:Label runat="server" Text='<%#Eval("LectureName") %>'></asp:Label></b>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField HeaderText="Lecture Description" DataField="LectureDescription" />
                       
                        <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="Watch" runat="server" OnClick="Watch_Click">Watch Lecture</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Options">
                            <ItemTemplate>
                                <asp:Button ID="btnDelete" runat="server" Text="Delete" CssClass="btn btn-danger btn-xs" OnClick="btnDelete_Click" />
                            </ItemTemplate>

                        </asp:TemplateField>

                        
                    </Columns>
                </asp:GridView>
              
            </div>

        </div>

</asp:Content>
