<%@ Page Title="" Language="C#" MasterPageFile="~/StudentMaster.master" AutoEventWireup="true" CodeFile="WatchLectures.aspx.cs" Inherits="WatchLectures" %>
<%@ MasterType VirtualPath="~/StudentMaster.master" %>

<asp:Content ID="Content5" ContentPlaceHolderID="Heading500" Runat="Server">
      <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Courses
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i><a href="SDashboard.aspx"> Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-book"></i> Workshop Progress
                </li>
                <li class="active"> Watch Lectures
                </li>
            </ol>
        </div>
    </div>
</asp:Content>

<asp:Content ID="Content10" ContentPlaceHolderID="WatchLectures" Runat="Server">
      <center>  <asp:PlaceHolder ID="DBDataPlaceHolder" runat="server"></asp:PlaceHolder>  </center> 
        <div class="col-lg-12">
            <div class="center-block">
               
                <asp:GridView runat="server" DataKeyNames="Id" OnRowDataBound="grdStudents_RowDataBound"  ID="grdStudents" CssClass="table table-bordered table-hover table-responsive" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateColumns="false">
                    <Columns>

                        <asp:BoundField ReadOnly="true" HeaderText="Lecture No." DataField="Id"  />
                        
                        <asp:TemplateField HeaderText="Lecture Title">
                            <ItemTemplate>
                                <b>
                                    <asp:Label runat="server" Text='<%#Eval("LectureName") %>'></asp:Label></b>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField HeaderText="Lecture Description" DataField="LectureDescription" />
                         <asp:BoundField HeaderText="Lecturer" DataField="instructor_name" />
                        <asp:TemplateField HeaderText="">
                            <ItemTemplate>
                                <asp:LinkButton ID="Watch" runat="server" OnClick="Watch_Click">Watch Lecture</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        

                        
                    </Columns>
                </asp:GridView>
              
            </div>

        </div>

</asp:Content>

